import 'package:flutter/material.dart';

const Color kColorA = Color(0xff55efc4);
const Color kColorB = Color(0xff81ecec);
const Color kColorC = Color(0xff74b9ff);
const Color kColorD = Color(0xffa29bfe);
const Color kColorE = Color(0xffdfe6e9);
const Color kColorF = Color(0xff00b894);
const Color kColorG = Color(0xff00cec9);
const Color kColorH = Color(0xff0984e3);
const Color kColorI = Color(0xff6c5ce7);
const Color kColorJ = Color(0xffb2bec3);
const Color kColorK = Color(0xffffeaa7);
const Color kColorL = Color(0xfffab1a0);
const Color kColorM = Color(0xffff7675);
const Color kColorN = Color(0xfffd79a8);
const Color kColorO = Color(0xff636e72);
const Color kColorP = Color(0xfffdcb6e);
const Color kColorQ = Color(0xffe17055);
const Color kColorX = Color(0xffd63031);
const Color kColorZ = Color(0xffe84393);
